name: CI-CD
on:
  push:
    branches: ["main"]
  workflow_dispatch:
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    
      - name: Obtendo o codigo do projeto
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}




      -  name: Contrução da Imagem Docker
         uses: docker/build-push-action@v6
         with:
          context: ./src
          push: true
          file: ./src/Dockerfile
          tags: |
            alissonws/fake-shop:latest
            alissonws/fake-shop:v${{ github.run_number }}







  cd:
    runs-on: ubuntu-latest
    needs: [ci]
    steps:
      - name: Autenticar n AWS
        run: echo "Executando o comando aws conbfigure"
      - name: Configurar o kubectl
        run: echo "Executando o comando aws eks update-kubeconfig "
      - name: Deploy dos manifestos no Kubernetes
        run: echo "Executando o comando kubectl apply"
      
